# Query the Capstone Project Data in Redshift

In [1]:
%load_ext sql

In [2]:
import configparser
import pandas as pd
import os
import boto3
import json

In [3]:
config = configparser.ConfigParser()
config.read('dl.cfg')

['dl.cfg']

In [4]:
os.environ['AWS_ACCESS_KEY_ID']=config['AWS']['AWS_ACCESS_KEY_ID']
os.environ['AWS_SECRET_ACCESS_KEY']=config['AWS']['AWS_SECRET_ACCESS_KEY']

In [5]:
DWH_ENDPOINT=config['DWH']['DWH_ENDPOINT']
DWH_DB=config['DWH']['DWH_DB']
DWH_DB_USER=config['DWH']['DWH_DB_USER']
DWH_DB_PASSWORD=config['DWH']['DWH_DB_PASSWORD']
DWH_PORT=config['DWH']['DWH_PORT']

In [ ]:
conn_string="postgresql://{}:{}@{}:{}/{}".format(DWH_DB_USER, DWH_DB_PASSWORD, DWH_ENDPOINT, DWH_PORT,DWH_DB)
print(conn_string)
%sql $conn_string

## Qurey Dimension Table row count

In [7]:
%%time
qry = """
    select count(*) from countries
"""
nCountries= %sql $qry
qry = """
    select count(*) from leagues
"""
nLeagues= %sql $qry
qry = """
    select count(*) from teams
"""
nTeams= %sql $qry
qry = """
    select count(*) from venues
"""
nVenues= %sql $qry
qry = """
    select count(*) from players
"""
nPlayers= %sql $qry
qry = """
    select count(*) from fixtures
"""
nFixtures= %sql $qry
qry = """
    select count(*) from lineups
"""
nLineups= %sql $qry

print("countries\t\t=", nCountries[0][0])
print("leagues\t\t=", nLeagues[0][0])
print("teams\t\t=", nTeams[0][0])
print("venues\t\t=", nVenues[0][0])
print("players\t\t=", nPlayers[0][0])
print("fixtures\t\t=", nFixtures[0][0])
print("lineups\t\t=", nLineups[0][0])

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
countries		= 167
leagues		= 5040
teams		= 130850
venues		= 61398
players		= 153996
fixtures		= 950451
lineups		= 989382
CPU times: user 27.7 ms, sys: 7.47 ms, total: 35.2 ms
Wall time: 2.62 s

## Qurey Fact Table row count

In [8]:
%%time
qry = """
    select count(*) from player_statistics
"""
nPlayer_statistics= %sql $qry
qry = """
    select count(*) from match_statistics
"""
nMatch_statistics= %sql $qry
qry = """
    select count(*) from league_standings
"""
nLeague_standings= %sql $qry

print("player_statistics\t\t=", nPlayer_statistics[0][0])
print("match_statistics\t\t=", nMatch_statistics[0][0])
print("league_standings\t\t=", nLeague_standings[0][0])

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
player_statistics		= 619255
match_statistics		= 11524
league_standings		= 70992
CPU times: user 12.2 ms, sys: 4.02 ms, total: 16.2 ms
Wall time: 997 ms

## Query Premier League Teams

In [9]:
%%time
%%sql
SELECT id, season, name, code, country, league_id, founded, venue_id FROM teams WHERE league_id = 39 AND season=2022

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
20 rows affected.
CPU times: user 4.65 ms, sys: 2.22 ms, total: 6.87 ms
Wall time: 464 ms

[(35, 2022, 'Bournemouth', 'BOU', 'England', 39, 1899, 504),
 (47, 2022, 'Tottenham', 'TOT', 'England', 39, 1882, 593),
 (51, 2022, 'Brighton', 'BRI', 'England', 39, 1901, 508),
 (34, 2022, 'Newcastle', 'NEW', 'England', 39, 1892, 562),
 (40, 2022, 'Liverpool', 'LIV', 'England', 39, 1892, 550),
 (63, 2022, 'Leeds', 'LEE', 'England', 39, 1919, 546),
 (33, 2022, 'Manchester United', 'MUN', 'England', 39, 1878, 556),
 (45, 2022, 'Everton', 'EVE', 'England', 39, 1878, 8560),
 (48, 2022, 'West Ham', 'WES', 'England', 39, 1895, 598),
 (52, 2022, 'Crystal Palace', 'CRY', 'England', 39, 1905, 525),
 (39, 2022, 'Wolves', 'WOL', 'England', 39, 1877, 600),
 (49, 2022, 'Chelsea', 'CHE', 'England', 39, 1905, 519),
 (55, 2022, 'Brentford', 'BRE', 'England', 39, 1889, 10503),
 (36, 2022, 'Fulham', 'FUL', 'England', 39, 1879, 535),
 (46, 2022, 'Leicester', 'LEI', 'England', 39, 1884, 547),
 (66, 2022, 'Aston Villa', 'AST', 'England', 39, 1874, 495),
 (41, 2022, 'Southampton', 'SOU', 'England', 39, 1885, 585),
 (65, 2022, 'Nottingham Forest', 'NOT', 'England', 39, 1865, 566),
 (42, 2022, 'Arsenal', 'ARS', 'England', 39, 1886, 494),
 (50, 2022, 'Manchester City', 'MAC', 'England', 39, 1880, 555)]

## Query Premier League Manchester City Team Fixture

In [10]:
%%time
%%sql
SELECT a.id as fixture_id, a.fixture_date, a.fixture_time, a.referee, a.status_elapsed,
        a. status_long, a.status_short, a.timezone, 
        a.teams_home_id, b.name as team_home_name, a.goals_home,
        a.score_extratime_home, a.score_fulltime_home, a.score_halftime_home,  a.score_penalty_home,
        a.teams_away_id, c.name as team_away_name, a.goals_away,
        a.score_extratime_away, a.score_fulltime_away, a.score_halftime_away, a.score_penalty_away,
        case when teams_home_winner is true then b.name
             when teams_away_winner is true then c.name
             else '' end as winner, 
        c.country as team_country, f.name as venue_name, f.city, 
        d.name as league_name, d.seasons_year, d.country_name, e.code as country_code, a.league_round
        FROM fixtures a 
        LEFT JOIN TEAMS b
        on a.teams_home_id = b.id
        AND a.league_season = b.season
        AND a.league_id = b.league_id
        LEFT JOIN TEAMS c
        on a.teams_away_id = c.id
        AND a.league_season = c.season
        AND a.league_id = c.league_id
        LEFT JOIN LEAGUES d
        on a.league_id = d.id
        AND a.league_season = d.seasons_year
        LEFT JOIN countries e
        on d.country_name = e.name
        LEFT JOIN venues f
        on a.venue_id = f.id
        where a.league_id = 39 
        and a.teams_home_id = 50
        and a.league_season = 2022
        limit 5;

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
5 rows affected.
CPU times: user 11.2 ms, sys: 2.43 ms, total: 13.6 ms
Wall time: 969 ms

[(867962, datetime.date(2022, 8, 13), datetime.time(14, 0), 'David Coote, England', 90, 'Match Finished', 'FT', 'UTC', 50, 'Manchester City', 4, None, 4, 3, None, 35, 'Bournemouth', 0, None, 0, 0, None, 'Manchester City', 'England', 'Etihad Stadium', 'Manchester', 'Premier League', 2022, 'England', 'GB', 'Regular Season - 2'),
 (868013, datetime.date(2023, 1, 19), datetime.time(20, 0), 'Simon Hooper, England', 90, 'Match Finished', 'FT', 'UTC', 50, 'Manchester City', 4, None, 4, 0, None, 47, 'Tottenham', 2, None, 2, 2, None, 'Manchester City', 'England', 'Etihad Stadium', 'Manchester', 'Premier League', 2022, 'England', 'GB', 'Regular Season - 7'),
 (868232, datetime.date(2023, 4, 1), datetime.time(11, 30), 'Simon Hooper, England', 90, 'Match Finished', 'FT', 'UTC', 50, 'Manchester City', 4, None, 4, 1, None, 40, 'Liverpool', 1, None, 1, 1, None, 'Manchester City', 'England', 'Etihad Stadium', 'Manchester', 'Premier League', 2022, 'England', 'GB', 'Regular Season - 29'),
 (868290, datetime.date(2023, 5, 6), datetime.time(14, 0), 'Andy Madley, England', 90, 'Match Finished', 'FT', 'UTC', 50, 'Manchester City', 2, None, 2, 2, None, 63, 'Leeds', 1, None, 1, 0, None, 'Manchester City', 'England', 'Etihad Stadium', 'Manchester', 'Premier League', 2022, 'England', 'GB', 'Regular Season - 35'),
 (868033, datetime.date(2022, 10, 2), datetime.time(13, 0), 'Michael Oliver, England', 90, 'Match Finished', 'FT', 'UTC', 50, 'Manchester City', 6, None, 6, 4, None, 33, 'Manchester United', 3, None, 3, 0, None, 'Manchester City', 'England', 'Etihad Stadium', 'Manchester', 'Premier League', 2022, 'England', 'GB', 'Regular Season - 9')]

## Query Premier League Fixture Information by Fixture ID

In [11]:
%%time
%%sql
SELECT a.id as fixture_id, a.fixture_date, a.fixture_time, a.referee, a.status_elapsed,
        a. status_long, a.status_short, a.timezone, 
        a.teams_home_id, b.name as team_home_name, a.goals_home,
        a.score_extratime_home, a.score_fulltime_home, a.score_halftime_home,  a.score_penalty_home,
        a.teams_away_id, c.name as team_away_name, a.goals_away,
        a.score_extratime_away, a.score_fulltime_away, a.score_halftime_away, a.score_penalty_away,
        case when teams_home_winner is true then b.name
             when teams_away_winner is true then c.name
             else '' end as winner, 
        c.country as team_country, f.name as venue_name, f.city, 
        d.name as league_name, d.seasons_year, d.country_name, e.code as league_code, a.league_round
        FROM fixtures a 
        LEFT JOIN teams b
        on a.teams_home_id = b.id
        AND a.league_season = b.season
        AND a.league_id = b.league_id
        LEFT JOIN teams c
        on a.teams_away_id = c.id
        AND a.league_season = c.season
        AND a.league_id = c.league_id
        LEFT JOIN leagues d
        on a.league_id = d.id
        AND a.league_season = d.seasons_year
        LEFT JOIN countries e
        on d.country_name = e.name
        LEFT JOIN venues f
        on a.venue_id = f.id
        and d.seasons_year = f.season
        where a.id = 868033

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
CPU times: user 11.5 ms, sys: 2.51 ms, total: 14 ms
Wall time: 4.3 s

[(868033, datetime.date(2022, 10, 2), datetime.time(13, 0), 'Michael Oliver, England', 90, 'Match Finished', 'FT', 'UTC', 50, 'Manchester City', 6, None, 6, 4, None, 33, 'Manchester United', 3, None, 3, 0, None, 'Manchester City', 'England', 'Etihad Stadium', 'Manchester', 'Premier League', 2022, 'England', 'GB', 'Regular Season - 9')]

## Query Premier League Match Lineups by Fixture ID

In [12]:
%%time
%%sql
SELECT a.formation, a.team_id, a.season, b.name as team_name, 
        a.fixture_id, a.player_id, c.name as player_name, c.nationality,  
        a.player_number, a.player_pos, a.player_grid, a.lineup_type, 
        a.coach_id, a.coach_name, d.name as league_name, d.seasons_year,
        d.country_name, e.code as country_code
        FROM lineups a 
        LEFT JOIN fixtures g
        on a.fixture_id = g.id
        LEFT JOIN teams b
        on a.team_id = b.id
        AND a.season = b.season
        AND g.league_id = b.league_id
        LEFT JOIN players c
        on a.player_id = c.id
        LEFT JOIN leagues d
        on g.league_id = d.id
        AND g.league_season = d.seasons_year
        LEFT JOIN countries e
        on d.country_name = e.name  
        where fixture_id= 868033
        AND lineup_type='starter'
        order by a.team_id, a.player_id;

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
22 rows affected.
CPU times: user 9.24 ms, sys: 2.6 ms, total: 11.8 ms
Wall time: 1.14 s

[('4-2-3-1', 33, 2022, 'Manchester United', 868033, 18, 'Jadon Malik Sancho', 'England', 25, 'M', '4:1', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 174, 'C. Eriksen', 'Denmark', 14, 'M', '3:1', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 742, 'R. Varane', 'France', 19, 'D', '2:3', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 882, 'David de Gea', 'Spain', 1, 'G', '1:1', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 886, 'Diogo Dalot', 'Portugal', 20, 'D', '2:4', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 903, 'S. McTominay', 'Scotland', 39, 'M', '3:2', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 909, 'M. Rashford', 'England', 10, 'F', '5:1', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 1485, 'Bruno Fernandes', 'Portugal', 8, 'M', '4:2', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 2467, 'Lisandro Martínez', 'Argentina', 6, 'D', '2:2', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 9971, 'Antony Matheus dos Santos', 'Brazil', 21, 'M', '4:3', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-2-3-1', 33, 2022, 'Manchester United', 868033, 37145, 'T. Malacia', 'Netherlands', 12, 'D', '2:1', 'starter', 1993, 'E. ten Hag', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 5, 'M. Akanji', 'Switzerland', 25, 'D', '2:3', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 617, 'Ederson', 'Brazil', 31, 'G', '1:1', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 627, 'K. Walker', 'England', 2, 'D', '2:4', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 629, 'K. De Bruyne', 'Belgium', 17, 'M', '3:3', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 631, 'P. Foden', 'England', 47, 'F', '4:3', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 633, 'İ. Gündoğan', 'Germany', 8, 'M', '3:2', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 636, 'Bernardo Silva', 'Portugal', 20, 'M', '3:1', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 855, 'João Cancelo', 'Portugal', 7, 'D', '2:1', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 1100, 'Erling Braut Haaland', 'Norway', 9, 'F', '4:2', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 18861, 'N. Aké', 'Netherlands', 6, 'D', '2:2', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB'),
 ('4-3-3', 50, 2022, 'Manchester City', 868033, 19187, 'J. Grealish', 'England', 10, 'F', '4:1', 'starter', 4, 'Pep Guardiola', 'Premier League', 2022, 'England', 'GB')]

## Query Premier League Fact Table Match Statistic by Fixture ID

In [13]:
%%time
%%sql
SELECT  b.name as team_name, a.fixture_id, c.name as league_name, a.league_season, e.name as venue,
        c.country_name, Shots_on_Goal, Shots_off_Goal, Total_Shots, Blocked_Shots,
        Shots_insidebox, Shots_outsidebox, Fouls, Corner_Kicks, Offsides,
        Ball_Possession, Yellow_Cards, Red_Cards, Goalkeeper_Saves, Total_passes,
        Passes_accurate,Passes_percentage  
        FROM match_statistics a 
        LEFT JOIN teams b
        on a.team_id = b.id
        AND a.league_season = b.season
        AND a.league_id = b.league_id 
        LEFT JOIN LEAGUES c
        on a.league_id = c.id
        AND a.league_season = c.seasons_year
        LEFT JOIN fixtures d
        on a.fixture_id = c.id
        LEFT JOIN venues e
        on a.venue_id = e.id
        and a.league_season = e.season
        WHERE fixture_id = 868033

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
2 rows affected.
CPU times: user 8.83 ms, sys: 2.32 ms, total: 11.1 ms
Wall time: 470 ms

[('Manchester United', 868033, 'Premier League', 2022, 'Etihad Stadium', 'England', 8, 1, 12, 3, 6, 6, 9, 1, None, '46%', 3, None, 3, 476, 408, '86%'),
 ('Manchester City', 868033, 'Premier League', 2022, 'Etihad Stadium', 'England', 10, 6, 22, 6, 17, 5, 3, 5, 1, '54%', None, None, 5, 551, 485, '88%')]

## Query Premier League Fact Table Player Statistic by Player ID

In [14]:
%%time
%%sql
SELECT a.player_id,  c.name as player_name, c.nationality, a.team_id, b.name as team_name, 
e.name as venues, d.name as league, d.country_name as league_country, game_appearences, 
game_lineups, game_minutes, game_number, game_position,game_rating, game_captain, substitute_in, 
substitute_out, substitute_bench, shot_total,
shot_on, goal_total, goal_conceded, goal_assists, goal_saves,
pass_total, pass_key, pass_accuracy, tackle_total, tackle_blocks, tackle_interceptions,
duel_total, duel_won, dribble_attempts, dribble_success, dribble_past,
foul_drawn, foul_committed, card_yellow, card_yellowred, card_red,
penalty_won, penalty_commited, penalty_scored, penalty_missed, penalty_saved
FROM player_statistics a 
LEFT JOIN teams b
ON a.team_id = b.id
AND a.league_season = b.season
AND a.league_id = b.league_id 
LEFT JOIN players c
ON a.player_id = c.id
LEFT JOIN leagues d
ON a.league_id = d.id
AND a.league_season = d.seasons_year
LEFT JOIN venues e
on a.venue_id = e.id
and a.league_season = e.season
WHERE a.player_id = 629   
AND a.league_season = 2022
AND a.league_id = 39

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
1 rows affected.
CPU times: user 10.6 ms, sys: 13.1 ms, total: 23.7 ms
Wall time: 4.29 s

[(629, 'K. De Bruyne', 'Belgium', 50, 'Manchester City', 'Etihad Stadium', 'Premier League', 'England', 23, 21, 1868, None, 'Midfielder', '7.773913', False, 2, 8, 3, 38, 18, 4, 0, 12, None, 981, 76, 33, 20, 2, 5, 148, 66, 32, 19, None, 19, 17, 1, 0, 0, None, None, 0, 0, None)]

## Query Premier League Fact Table League Standings by League ID

In [15]:
%%time
%%sql
SELECT  a.league_id, b.name as league, a.league_season, b.country_name as league_contry, 
        c.name as team, d.name as venue, rank, points, goalsDiff, standings_group, 
        form, status, description, update_date, update_time, 
        all_played, all_win, all_draw, all_lose, all_goals_for,
        all_goals_against, home_played, home_win, home_draw,
        home_lose, home_goals_for, home_goals_against, away_played, away_win,
        away_draw, away_lose, away_goals_for,
        away_goals_against   
        FROM league_standings a
        LEFT JOIN leagues b 
        ON a.league_id = b.id
        AND a.league_season = b.seasons_year
        LEFT JOIN teams c
        ON a. team_id = c.id 
        AND a.league_season = c.season
        AND a.league_id = c.league_id
        LEFT JOIN venues d
		ON a.venue_id = d.id
        AND a.league_season = d.season
        WHERE a.league_id = 39
        AND a.league_season = 2022
        AND a.standings_index = 0
        ORDER BY rank

 * postgresql://awsuser:***@redshift-cluster-1.c5bgenlwkhbm.us-west-2.redshift.amazonaws.com:5439/dev
20 rows affected.
CPU times: user 10.6 ms, sys: 15.7 ms, total: 26.3 ms
Wall time: 4.3 s

[(39, 'Premier League', 2022, 'England', 'Manchester City', 'Etihad Stadium', 1, 85, None, 'Premier League', 'WWWWW', 'same', 'Promotion - Champions League (Group Stage: )', datetime.date(2023, 5, 15), datetime.time(0, 0), 35, 27, 4, 4, 92, 31, 18, 16, 1, 1, 59, 17, 17, 11, 3, 3, 33, 14),
 (39, 'Premier League', 2022, 'England', 'Arsenal', 'Emirates Stadium', 2, 81, None, 'Premier League', 'LWWLD', 'same', 'Promotion - Champions League (Group Stage: )', datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 25, 6, 5, 83, 42, 18, 13, 3, 2, 48, 25, 18, 12, 3, 3, 35, 17),
 (39, 'Premier League', 2022, 'England', 'Newcastle', "St. James' Park", 3, 66, None, 'Premier League', 'DLWWW', 'same', 'Promotion - Champions League (Group Stage: )', datetime.date(2023, 5, 15), datetime.time(0, 0), 35, 18, 12, 5, 63, 31, 17, 10, 5, 2, 32, 13, 18, 8, 7, 3, 31, 18),
 (39, 'Premier League', 2022, 'England', 'Manchester United', 'Old Trafford', 4, 66, None, 'Premier League', 'WLLWD', 'same', 'Promotion - Champions League (Group Stage: )', datetime.date(2023, 5, 15), datetime.time(0, 0), 35, 20, 6, 9, 51, 41, 17, 13, 3, 1, 30, 8, 18, 7, 3, 8, 21, 33),
 (39, 'Premier League', 2022, 'England', 'Liverpool', 'Anfield', 5, 62, None, 'Premier League', 'WWWWW', 'same', 'Promotion - Europa League (Group Stage: )', datetime.date(2023, 5, 15), datetime.time(0, 0), 35, 18, 8, 9, 67, 42, 18, 13, 4, 1, 45, 16, 17, 5, 4, 8, 22, 26),
 (39, 'Premier League', 2022, 'England', 'Brighton', 'The American Express Community Stadium', 6, 58, None, 'Premier League', 'WLWWL', 'same', 'Promotion - Europa League (Group Stage: )', datetime.date(2023, 5, 15), datetime.time(0, 0), 34, 17, 7, 10, 66, 45, 17, 9, 3, 5, 33, 19, 17, 8, 4, 5, 33, 26),
 (39, 'Premier League', 2022, 'England', 'Tottenham', 'Tottenham Hotspur Stadium', 7, 57, None, 'Premier League', 'LWLDL', 'same', 'Promotion - Europa Conference League (Qualification: )', datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 17, 6, 13, 65, 59, 18, 12, 1, 5, 36, 22, 18, 5, 5, 8, 29, 37),
 (39, 'Premier League', 2022, 'England', 'Aston Villa', 'Villa Park', 8, 57, None, 'Premier League', 'WLLWD', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 17, 6, 13, 48, 44, 18, 11, 2, 5, 31, 20, 18, 6, 4, 8, 17, 24),
 (39, 'Premier League', 2022, 'England', 'Brentford', 'Gtech Community Stadium', 9, 53, None, 'Premier League', 'WLWWD', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 13, 14, 9, 54, 45, 18, 9, 7, 2, 34, 18, 18, 4, 7, 7, 20, 27),
 (39, 'Premier League', 2022, 'England', 'Fulham', 'Craven Cottage', 10, 51, None, 'Premier League', 'WWLLL', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 15, 6, 15, 52, 49, 18, 8, 4, 6, 29, 27, 18, 7, 2, 9, 23, 22),
 (39, 'Premier League', 2022, 'England', 'Chelsea', 'Stamford Bridge', 11, 43, None, 'Premier League', 'DWLLL', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 35, 11, 10, 14, 36, 41, 18, 6, 6, 6, 19, 18, 17, 5, 4, 8, 17, 23),
 (39, 'Premier League', 2022, 'England', 'Crystal Palace', 'Selhurst Park', 12, 43, None, 'Premier League', 'WLWLD', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 11, 10, 15, 37, 46, 18, 7, 6, 5, 20, 22, 18, 4, 4, 10, 17, 24),
 (39, 'Premier League', 2022, 'England', 'Wolves', 'Molineux Stadium', 13, 40, None, 'Premier League', 'LWLWL', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 11, 7, 18, 30, 52, 18, 9, 2, 7, 18, 19, 18, 2, 5, 11, 12, 33),
 (39, 'Premier League', 2022, 'England', 'Bournemouth', 'Vitality Stadium', 14, 39, None, 'Premier League', 'LLWWL', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 11, 6, 19, 37, 69, 18, 6, 4, 8, 20, 27, 18, 5, 2, 11, 17, 42),
 (39, 'Premier League', 2022, 'England', 'West Ham', 'London Stadium', 15, 37, None, 'Premier League', 'LWLLL', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 10, 7, 19, 38, 52, 18, 7, 4, 7, 23, 23, 18, 3, 3, 12, 15, 29),
 (39, 'Premier League', 2022, 'England', 'Nottingham Forest', 'The City Ground', 16, 34, None, 'Premier League', 'DWLWL', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 8, 10, 18, 36, 67, 18, 7, 6, 5, 26, 24, 18, 1, 4, 13, 10, 43),
 (39, 'Premier League', 2022, 'England', 'Everton', 'Goodison Park', 17, 32, None, 'Premier League', 'LWDLD', 'same', None, datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 7, 11, 18, 32, 56, 18, 5, 3, 10, 15, 27, 18, 2, 8, 8, 17, 29),
 (39, 'Premier League', 2022, 'England', 'Leeds', 'Elland Road', 18, 31, None, 'Premier League', 'DLLDL', 'same', 'Relegation - Championship', datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 7, 10, 19, 46, 71, 18, 5, 7, 6, 25, 33, 18, 2, 3, 13, 21, 38),
 (39, 'Premier League', 2022, 'England', 'Leicester', 'King Power Stadium', 19, 30, None, 'Premier League', 'LDDWL', 'same', 'Relegation - Championship', datetime.date(2023, 5, 15), datetime.time(0, 0), 35, 8, 6, 21, 49, 64, 17, 4, 4, 9, 21, 23, 18, 4, 2, 12, 28, 41),
 (39, 'Premier League', 2022, 'England', 'Southampton', "St. Mary's Stadium", 20, 24, None, 'Premier League', 'LLLLD', 'same', 'Relegation - Championship', datetime.date(2023, 5, 15), datetime.time(0, 0), 36, 6, 6, 24, 31, 66, 18, 2, 4, 12, 15, 33, 18, 4, 2, 12, 16, 33)]